#Keybinds

$blurSpecialWs = true #false
$fileExplorer = thunar 
$editor = code
$workspaceGaps = 06
$windowGapsIn = 04
$windowGapsOut = 04
$singleWindowGapsOut = 06
$windowOpacity = 0.90
$windowRounding = 8 #10
$windowBorderSize = 0 #3
$cursorSize = 20
$kbMoveWindow = Super, ZA
$kbToggleWindowFloating = Super, W #Super+Alt, Space
$kbTerminal = Super, Return
$kbBrowser = Super, Z
$kbSession = Super, Delete


