#Startup Files
exec-once = /home/samonide/seanime
#exec-once = fcitx5

#Custom Keybinds
binddel = , F10, $d decrease volume , exec, /home/samonide/.config/caelestia/volumecontrol.sh -o d # decrease volume
binddel = , F12, $d increase volume , exec, /home/samonide/.config/caelestia/volumecontrol.sh -o i # increase volume
binddl  = , F9, $d toggle mute output , exec, /home/samonide/.config/caelestia/volumecontrol.sh -o m # toggle audio mute

#execs
exec-once = qs -c overview


#Personal
bind = Super, tab, workspace, m+1
bind = Super, A, exec, qs ipc -c overview call overview toggle


# Move focused window to a workspace
$d=[$ws|Move window to workspace]
bindd = Super Shift, 1, $d move to workspace 1 , movetoworkspace, 1
bindd = Super Shift, 2, $d move to workspace 2 , movetoworkspace, 2
bindd = Super Shift, 3, $d move to workspace 3 , movetoworkspace, 3
bindd = Super Shift, 4, $d move to workspace 4 , movetoworkspace, 4
bindd = Super Shift, 5, $d move to workspace 5 , movetoworkspace, 5
bindd = Super Shift, 6, $d move to workspace 6 , movetoworkspace, 6
bindd = Super Shift, 7, $d move to workspace 7 , movetoworkspace, 7
bindd = Super Shift, 8, $d move to workspace 8 , movetoworkspace, 8
bindd = Super Shift, 9, $d move to workspace 9 , movetoworkspace, 9
bindd = Super Shift, 0, $d move to workspace 10 , movetoworkspace, 10




bindd = Super, J, Toggle bar, global, quickshell:barToggle # Toggle bar

bind = Super, J, exec, caelestia shell drawers toggle sidebar

#Display Res
monitor = , highrr, auto, 1

